### PR TITLE
BZ #1198973: Add MTU config to all interfaces involved

### PR DESCRIPTION
**Pull request by bcrochet**
When a VLAN is on top of a bond, MTU should be added to all config files
involved in the chain, including physical interfaces, the bond, and the
VLAN.

### CODE REVIEW

**Comment by sseago** [comment]
looks good to me.

**Comment by jistr** [comment]
LGTM

**Comment by sseago** [comment]
Looks good with the last change too.

**Comment by mburns72h** [comment]
ACK, merge away

**Pull request merged**
